[package]
name = "minigrep"
version = "0.1.0"
authors = ["56428 <48052798@qq.com>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib.rs"

[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
