[package]
name = "demobin"
version = "0.1.0"
authors = ["56428"]
edition = "2018"

[lib]
name = "flycoin"
path = "src/flycoin.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
