[package]
name = "consensus"
version = "0.1.0"
authors = ["56428 <48052798@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
reqwest = "0.9.20"
serde = "1.0.60"
serde_json = "1.0.40"